version: "3.9"

services:
  runner:
    image: gitlab/gitlab-runner:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    volumes:
      - ./conf.d/runner:/etc/gitlab-runner
      - ./ssh_keys/runner:/home/runner.pem
      - /var/run/docker.sock:/var/run/docker.sock
